[package]
name = "kdb"
version = "0.1.0"
authors = ["ztgx"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lmdb-zero = "0.4.4"

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"
